// Create hash map of file location to schema data, to avoid dynamic import statements,
// making it easier for JS bundlers (i.e. ESBuild)

const schemaMap = {
  "asset_collection/full.json": require("../schemas/asset_collection/full.json"),
  "asset_collection/types.json": require("../schemas/asset_collection/types.json"),
  "asset_collection/update.json": require("../schemas/asset_collection/update.json"),
  "experience/with_production.json": require("../schemas/experience/with_production.json"),
  "experience/without_production.json": require("../schemas/experience/without_production.json"),
  "meta/meta.json": require("../schemas/meta/meta.json"),
  "meta/romper_meta.json": require("../schemas/meta/romper_meta.json"),
  "meta/storygraph_meta.json": require("../schemas/meta/storygraph_meta.json"),
  "meta/storyplayer_meta.json": require("../schemas/meta/storyplayer_meta.json"),
  "meta/storyshooter_meta.json": require("../schemas/meta/storyshooter_meta.json"),
  "narrative_element/full.json": require("../schemas/narrative_element/full.json"),
  "narrative_element/types.json": require("../schemas/narrative_element/types.json"),
  "narrative_element/update.json": require("../schemas/narrative_element/update.json"),
  "narrative_element_link/update.json": require("../schemas/narrative_element_link/update.json"),
  "production/full.json": require("../schemas/production/full.json"),
  "production/types.json": require("../schemas/production/types.json"),
  "production/update.json": require("../schemas/production/update.json"),
  "production_package/full.json": require("../schemas/production_package/full.json"),
  "production_package/types.json": require("../schemas/production_package/types.json"),
  "production_package/update.json": require("../schemas/production_package/update.json"),
  "representation/full.json": require("../schemas/representation/full.json"),
  "representation/types.json": require("../schemas/representation/types.json"),
  "representation/update.json": require("../schemas/representation/update.json"),
  "representation_choice/update.json": require("../schemas/representation/update.json"),
  "representation_collection/full.json": require("../schemas/representation_collection/full.json"),
  "representation_collection/types.json": require("../schemas/representation_collection/types.json"),
  "representation_collection/update.json": require("../schemas/representation_collection/update.json"),
  "representation_collection_represenation/update.json": require("../schemas/representation_collection_representation/update.json"),
  "rush/full.json": require("../schemas/rush/full.json"),
  "rush/types.json": require("../schemas/rush/types.json"),
  "rush/update.json": require("../schemas/rush/update.json"),
  "scene/full.json": require("../schemas/scene/full.json"),
  "scene/types.json": require("../schemas/scene/types.json"),
  "scene/update.json": require("../schemas/scene/update.json"),
  "shooting_schedule/full.json": require("../schemas/shooting_schedule/full.json"),
  "shooting_schedule/types.json": require("../schemas/shooting_schedule/types.json"),
  "shooting_schedule/update.json": require("../schemas/shooting_schedule/update.json"),
  "shot/full.json": require("../schemas/shot/full.json"),
  "shot/types.json": require("../schemas/shot/types.json"),
  "shot/update.json": require("../schemas/shot/update.json"),
  "story/full.json": require("../schemas/story/full.json"),
  "story/types.json": require("../schemas/story/types.json"),
  "story/update.json": require("../schemas/story/update.json"),
  "story_beginning/update.json": require("../schemas/story_beginning/update.json"),
  "core.json": require("../schemas/core.json"),
  "expression.json": require("../schemas/expression.json"),
  "uuids.json": require("../schemas/uuids.json")
}

module.exports = schemaMap
